env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Mr+zi3AuB97VV6agAiPSLh/mINN9xm+H/8h+UGWaL5yBvJ6S4UUXT+IR/bS2t/0OS/OFeINQ7CSETlrBGtWEaA90Feek40ojhvo4XXsfyr9GHmi5v1yyKtCURxKIPlKDwL9DoONwG2Q+Ach/GuuIWT2W/AIObj+uSRFsSBVqQZCzhWGX8hXVQ7rQtgRE3w/fJBKKv/9gxwMMh3jQb3uRFjebYc8orovGSg5RkVOAzhrKOsgDkp5YgrpmEWoko2vbbyCBccgW8pa96ZrY2T8eXQs7xcpOWfK0sQcH3P0gH98DNMmqYeVO+RmXMFj2+SdiyVDqoSn3M03ZGf8CE9W/OEqR6X940VMkIv2VTrEUJVGhhQsOIYw5S0f2dlWCRmI1kKuWOu3X5KZsD+yvNcNLiEi3GCCq9Xq8SyOtPipDN6HaAacjGPiJdvRbUNCXpLhW0NByKMsrlk/b9A9sbEF9WEck+6MgvwtGUClewMlxkkIalTH+U04wG5vMIBnocHs7jxscq03Hu1i2u7lLxgjincDETsoUsrwC5hJHlENM0EXJOlcZCr7IliNXNaUcrIDNoz5tCiqk0zQrLYGbkg2ngY3KpD5blsEET0EUPpBJ8uOowXf7u8AHwz5V3ryEN5JX9y1yrPN1EhIuxLTzsSB9DGQMtevlR9AMNdMYQsHZmzA="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "sutdmssd/bankwebapp"
      description: "<Your project description here>"
    notification_email: iinvest86@gmail.com
    build_command_prepend: "<Your build preprocessing command here>"
    build_command: "<Your build command here>"
    branch_pattern: coverity_scan
